apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tomcatdemoapp-deployment-8080
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
